name: Build and Test Container Image
on:
  release:
    types:
      - published
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  file-changes:
    name: Gather File Changes
    runs-on: ubuntu-latest
    outputs:
      chart: ${{ steps.changes.outputs.chart }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Gather file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: none
          filters: |
            chart:
              - chart/**

  build-image:
    name: Build Image
    needs:
      - file-changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Assemble metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          # We want to set the following tags:
          #  - `main` if executed for build on main branch
          #  - SemVer when running for a release
          tags: |
            type=ref,enable=${{ github.ref_name == 'main' }},event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
        # Only push when building for a tag or the main branch
        if: github.ref_type == 'tag' || (github.ref_type == 'branch' && github.ref_name == 'main')
      - name: Build multi-platform image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          # Only push when building for a tag or the main branch
          push:
            ${{ github.ref_type == 'tag' || (github.ref_type == 'branch' && github.ref_name ==
            'main') }}
          tags: ${{ steps.meta.outputs.tags }}
      # Only export and upload the image if used for testing
      - name: Export umage for test platform
        if: needs.file-changes.outputs.chart == 'true' && github.ref_type != 'tag'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          outputs: type=oci,dest=/tmp/image.tar
      - name: Upload image for testing
        uses: actions/upload-artifact@v3
        if: needs.file-changes.outputs.chart == 'true' && github.ref_type != 'tag'
        with:
          name: docker-image
          path: /tmp/image.tar

  e2e-tests:
    name: Test Helm Chart
    needs: [file-changes, build-image]
    runs-on: ubuntu-latest
    if: needs.file-changes.outputs.chart == 'true' && github.ref_type != 'tag'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install bats
        run: npm install -g bats@1.6.0
        shell: bash
      - name: Download image for testing
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: /tmp
      - name: Setup Kubernetes cluster
        uses: container-tools/kind-action@v2.0.0
        with:
          config: chart/tests/kind/actions.yaml
      - name: Import Docker image
        run: |
          IMAGE_ID=$(docker import /tmp/image.tar | rev | cut -d' ' -f1 | rev)
          docker tag $IMAGE_ID $KIND_REGISTRY/switchboard:dev
          docker push $KIND_REGISTRY/switchboard:dev
      - name: Set image tag
        run: |
            yq -i '
              .image.name = "${{ env.KIND_REGISTRY }}/switchboard" |
              .image.tag = "dev"
            ' chart/tests/values/base.yaml
      - name: Run tests
        run: bats ./tests -t
        working-directory: ./chart
